name: Update
on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
jobs:
  update:
    name: check, update and commit
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: setup python and locale
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: update data
        run: |
         ./update.py
      - name: commit
        run: |
          git config --global user.email "excepciones-bot@example.com"
          git config --global user.name "excepciones-bot"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "[ci] $(date '+%Y-%m-%d')"; git push -q "https://$GH_TOKEN@github.com/mauforonda/sl_excepciones.git" main)
